### PR TITLE
add the ability to use IAM instead of access and secret keys (#1)

### PR DESCRIPTION
**Pull request by cchristous**

### CODE REVIEW

**Comment by bermudezjd** [comment]
Any chance of getting this PR approved/merged?  It's useful/necessary for us.

**Comment by Restless-ET** [comment]
Hello @cchristous 

Sorry for the late reply but for some reason I didn't get an email notification about this PR. :|

I can totally merge this. I would just ask for you to add a note about the new role variable on the README please. :)

Regards,

**Comment by dmepham** [comment]
Hi @Restless-ET , I've made the suggested change. let me know if it looks good.
Thanks!

**Comment by Restless-ET** [comment]
Looks fine to me. I'll merge it and tag a new release. :)

**Comment by Restless-ET** [comment]
Merged, tagged and role re-imported on Galaxy. :)

Thanks for your contribution @cchristous and @dmepham

**Comment by dmepham** [comment]
Thank you!

**Pull request merged**
